package com.example.flighttrack.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties

/**
 * One aircraft entry from a single ADS-B snapshot.
 *
 * ## Flink POJO compliance (§ 4.2 – "no Kryo/GenericType warnings")
 * Flink avoids Kryo serialization when a class satisfies the POJO contract:
 *   1. Public class — Kotlin classes are public by default ✓
 *   2. No-arg constructor — generated by Kotlin when all fields have defaults ✓
 *   3. Public getter + setter per field — Kotlin `var` generates both ✓
 *
 * All fields are therefore `var` with a sensible default value.
 * Verify POJO detection at startup: Flink logs "AircraftRecord is a POJO type"
 * (INFO level). If you see "GenericType" instead, check for fields without
 * a corresponding public setter.
 *
 * ## Field naming
 * Raw ADS-B JSON uses terse, abbreviated keys (e.g. `hex`, `gs`, `r`, `t`).
 * This model uses full descriptive Kotlin names; [AircraftRecordParser] is
 * responsible for the mapping.
 *
 * ## Nullability
 * Only [hex] and [snapshotTime] are guaranteed to be present. Every other
 * field may be absent in a given broadcast, reflected as null / false / 0.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class AircraftRecord(

    /** ICAO 24-bit address (unique aircraft identifier). Always present. */
    var hex: String = "",

    /** Unix epoch timestamp (seconds) from the outer snapshot wrapper "now" field. */
    var snapshotTime: Double = 0.0,

    // ── Identity ──────────────────────────────────────────────────────────────

    /** Message source type: adsb_icao | adsr_icao | tisb_icao | mlat | … */
    var type: String? = null,

    /** Callsign / flight number as broadcast, trimmed of whitespace. */
    var flight: String? = null,

    /** Tail / registration number ("r" in raw JSON). */
    var registration: String? = null,

    /** ICAO aircraft type designator ("t" in raw JSON), e.g. B77W, A320. */
    var aircraftType: String? = null,

    // ── Altitude & vertical motion ────────────────────────────────────────────

    /**
     * Barometric altitude in feet ("alt_baro").
     * Null when the raw field is the string "ground" (aircraft on surface)
     * or when the field is absent entirely.
     */
    var altBaro: Int? = null,

    /** Geometric (GPS-derived) altitude in feet ("alt_geom"). */
    var altGeom: Int? = null,

    /** Vertical rate from barometric source, ft/min ("baro_rate"). Negative = descending. */
    var baroRate: Int? = null,

    /** Vertical rate from geometric source, ft/min ("geom_rate"). */
    var geomRate: Int? = null,

    // ── Horizontal motion ─────────────────────────────────────────────────────

    /** Ground speed in knots ("gs"). */
    var groundSpeed: Double? = null,

    /** True track / heading in degrees, 0–359 ("track"). */
    var track: Double? = null,

    // ── Transponder / ATC ─────────────────────────────────────────────────────

    /** 4-digit octal squawk code. Emergency codes: 7700 general, 7600 comms, 7500 hijack. */
    var squawk: String? = null,

    /** Emergency status: "none" | "general" | "lifeguard" | "minfuel" | "nordo" | … */
    var emergency: String? = null,

    /** Emitter category (A1–A7 = fixed-wing by weight, B1–B7 = rotor/glider, …). */
    var category: String? = null,

    // ── Position ──────────────────────────────────────────────────────────────

    /** WGS-84 latitude, degrees. Null when position has not been decoded yet. */
    var lat: Double? = null,

    /** WGS-84 longitude, degrees. Null when position has not been decoded yet. */
    var lon: Double? = null,

    /** Navigation Integrity Category (0 = unknown, 8 = ≤ 0.05 NM radius). */
    var nic: Int? = null,

    // ── Receiver quality ──────────────────────────────────────────────────────

    /** Seconds since the receiver last heard any message from this aircraft. */
    var seen: Double? = null,

    /** Seconds since the receiver last decoded a position for this aircraft. */
    var seenPos: Double? = null,

    /** Received signal strength, dBFS (negative; closer to 0 = stronger). */
    var rssi: Double? = null,

    /** Total messages received from this aircraft in the current receiver session. */
    var messages: Long? = null,

    // ── Navigation mode data ──────────────────────────────────────────────────

    /** Altimeter QNH setting selected by crew, hPa. */
    var navQnh: Double? = null,

    /** MCP/FCU selected altitude, feet. */
    var navAltitudeMcp: Int? = null,

    /** Selected heading, degrees. */
    var navHeading: Double? = null,

    // ── Source quality flags ──────────────────────────────────────────────────

    /**
     * True when the position was derived by multilateration (not ADS-B self-report).
     * Mapped from the raw "mlat" array: non-empty → true.
     */
    var mlat: Boolean = false,

    /**
     * True when data arrived via TIS-B rebroadcast from ground infrastructure.
     * Mapped from the raw "tisb" array: non-empty → true.
     */
    var tisb: Boolean = false,
)
